
package mx.unam.aragon.gui;

import java.util.ArrayList;
import mx.unam.aragon.dp.Empleado;

/**
 *
 * @author fernandasolange
 */
public class VentanaEmpleado extends javax.swing.JFrame {
    private ArrayList<Empleado> lista;
    /**
     * Creates new form VentanaEmpleado
     */
    public VentanaEmpleado() {
        initComponents();
        lista = new ArrayList<Empleado>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        PanelDatos = new javax.swing.JPanel();
        LabelNombre = new javax.swing.JLabel();
        FieldNombre = new javax.swing.JTextField();
        FieldApellidoPat = new javax.swing.JTextField();
        FieldApellidoMat = new javax.swing.JTextField();
        LabelEdad = new javax.swing.JLabel();
        FieldEdad = new javax.swing.JTextField();
        LabelCurp = new javax.swing.JLabel();
        FieldCurp = new javax.swing.JTextField();
        PanelDireccion = new javax.swing.JPanel();
        LabelCalle = new javax.swing.JLabel();
        FieldCalle = new javax.swing.JTextField();
        LabelNumero = new javax.swing.JLabel();
        FieldNumero = new javax.swing.JTextField();
        LabelColonia = new javax.swing.JLabel();
        FieldColonia = new javax.swing.JTextField();
        LabelDelegacion = new javax.swing.JLabel();
        FieldDelegacion = new javax.swing.JTextField();
        LabelEstado = new javax.swing.JLabel();
        LabelCp = new javax.swing.JLabel();
        FieldEstado = new javax.swing.JTextField();
        FieldCp = new javax.swing.JTextField();
        PanelEmpresariales = new javax.swing.JPanel();
        LabelEmpleado = new javax.swing.JLabel();
        FieldEmpleado = new javax.swing.JTextField();
        LabelDepartamento = new javax.swing.JLabel();
        FieldDepartamento = new javax.swing.JTextField();
        LabelSueldo = new javax.swing.JLabel();
        FieldSueldo = new javax.swing.JTextField();
        LabelHoras = new javax.swing.JLabel();
        FieldHoras = new javax.swing.JTextField();
        ButtonRegistro = new javax.swing.JButton();
        ButtonEnviar = new javax.swing.JButton();
        ButtonIzq = new javax.swing.JButton();
        ButtonDer = new javax.swing.JButton();
        ButtonCargar = new javax.swing.JButton();
        ButtonGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Base de datos empleado");

        jTabbedPane1.setBackground(new java.awt.Color(255, 102, 102));
        jTabbedPane1.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N

        PanelDatos.setBackground(new java.awt.Color(255, 153, 153));

        LabelNombre.setFont(new java.awt.Font("Avenir", 1, 14)); // NOI18N
        LabelNombre.setText("Nombre:  ");

        FieldNombre.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        FieldNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldNombreActionPerformed(evt);
            }
        });

        FieldApellidoPat.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N

        FieldApellidoMat.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N

        LabelEdad.setFont(new java.awt.Font("Avenir", 1, 14)); // NOI18N
        LabelEdad.setText("Edad:");

        FieldEdad.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N

        LabelCurp.setFont(new java.awt.Font("Avenir", 1, 14)); // NOI18N
        LabelCurp.setText("CURP:");

        FieldCurp.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N

        PanelDireccion.setBackground(new java.awt.Color(255, 204, 204));
        PanelDireccion.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.MatteBorder(null), "Dirección", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Avenir", 1, 14))); // NOI18N

        LabelCalle.setFont(new java.awt.Font("Avenir", 1, 14)); // NOI18N
        LabelCalle.setText("Calle:");

        FieldCalle.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N

        LabelNumero.setFont(new java.awt.Font("Avenir", 1, 14)); // NOI18N
        LabelNumero.setText("# Número: ");

        FieldNumero.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N

        LabelColonia.setFont(new java.awt.Font("Avenir", 1, 14)); // NOI18N
        LabelColonia.setText("Colonia:");

        FieldColonia.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N

        LabelDelegacion.setFont(new java.awt.Font("Avenir", 1, 14)); // NOI18N
        LabelDelegacion.setText("Delegación:");

        FieldDelegacion.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N

        LabelEstado.setFont(new java.awt.Font("Avenir", 1, 14)); // NOI18N
        LabelEstado.setText("Estado:");

        LabelCp.setFont(new java.awt.Font("Avenir", 1, 14)); // NOI18N
        LabelCp.setText("C.P.");

        FieldEstado.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N

        FieldCp.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N

        javax.swing.GroupLayout PanelDireccionLayout = new javax.swing.GroupLayout(PanelDireccion);
        PanelDireccion.setLayout(PanelDireccionLayout);
        PanelDireccionLayout.setHorizontalGroup(
            PanelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDireccionLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(PanelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDireccionLayout.createSequentialGroup()
                        .addComponent(LabelEstado)
                        .addGap(18, 18, 18)
                        .addComponent(FieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(LabelCp)
                        .addGap(18, 18, 18)
                        .addComponent(FieldCp, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDireccionLayout.createSequentialGroup()
                        .addComponent(LabelDelegacion)
                        .addGap(18, 18, 18)
                        .addComponent(FieldDelegacion, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDireccionLayout.createSequentialGroup()
                        .addComponent(LabelColonia)
                        .addGap(18, 18, 18)
                        .addComponent(FieldColonia, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelDireccionLayout.createSequentialGroup()
                        .addComponent(LabelCalle)
                        .addGap(18, 18, 18)
                        .addComponent(FieldCalle, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(LabelNumero)
                        .addGap(18, 18, 18)
                        .addComponent(FieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(227, Short.MAX_VALUE))
        );
        PanelDireccionLayout.setVerticalGroup(
            PanelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDireccionLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(PanelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCalle)
                    .addComponent(FieldCalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelNumero)
                    .addComponent(FieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelColonia)
                    .addComponent(FieldColonia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDelegacion)
                    .addComponent(FieldDelegacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDireccionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEstado)
                    .addComponent(LabelCp)
                    .addComponent(FieldEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldCp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelDatosLayout = new javax.swing.GroupLayout(PanelDatos);
        PanelDatos.setLayout(PanelDatosLayout);
        PanelDatosLayout.setHorizontalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelDatosLayout.createSequentialGroup()
                                .addComponent(LabelNombre)
                                .addGap(18, 18, 18)
                                .addComponent(FieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FieldApellidoPat, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(FieldApellidoMat, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelDatosLayout.createSequentialGroup()
                                .addComponent(LabelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(FieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelDatosLayout.createSequentialGroup()
                                .addComponent(LabelCurp)
                                .addGap(18, 18, 18)
                                .addComponent(FieldCurp, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(PanelDatosLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(PanelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        PanelDatosLayout.setVerticalGroup(
            PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDatosLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelNombre)
                    .addComponent(FieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldApellidoPat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldApellidoMat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEdad, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(FieldEdad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelDatosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelCurp)
                    .addComponent(FieldCurp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(PanelDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Datos personales", PanelDatos);

        PanelEmpresariales.setBackground(new java.awt.Color(255, 153, 153));
        PanelEmpresariales.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        PanelEmpresariales.setFont(new java.awt.Font("Avenir Next", 1, 13)); // NOI18N

        LabelEmpleado.setFont(new java.awt.Font("Avenir", 1, 14)); // NOI18N
        LabelEmpleado.setText("Número de empleado: ");

        FieldEmpleado.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N

        LabelDepartamento.setFont(new java.awt.Font("Avenir", 1, 14)); // NOI18N
        LabelDepartamento.setText("Departamento: ");

        FieldDepartamento.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N

        LabelSueldo.setFont(new java.awt.Font("Avenir", 1, 14)); // NOI18N
        LabelSueldo.setText("Sueldo (mensual):");

        FieldSueldo.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        FieldSueldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FieldSueldoActionPerformed(evt);
            }
        });

        LabelHoras.setFont(new java.awt.Font("Avenir", 1, 14)); // NOI18N
        LabelHoras.setText("Horas extra:");

        FieldHoras.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N

        javax.swing.GroupLayout PanelEmpresarialesLayout = new javax.swing.GroupLayout(PanelEmpresariales);
        PanelEmpresariales.setLayout(PanelEmpresarialesLayout);
        PanelEmpresarialesLayout.setHorizontalGroup(
            PanelEmpresarialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEmpresarialesLayout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addGroup(PanelEmpresarialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelSueldo)
                    .addComponent(LabelHoras)
                    .addComponent(LabelDepartamento)
                    .addComponent(LabelEmpleado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelEmpresarialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(FieldEmpleado, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addGroup(PanelEmpresarialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(FieldDepartamento, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(FieldHoras)
                        .addComponent(FieldSueldo)))
                .addContainerGap(413, Short.MAX_VALUE))
        );
        PanelEmpresarialesLayout.setVerticalGroup(
            PanelEmpresarialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelEmpresarialesLayout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(PanelEmpresarialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelEmpleado)
                    .addComponent(FieldEmpleado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelEmpresarialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelDepartamento)
                    .addComponent(FieldDepartamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelEmpresarialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelSueldo)
                    .addComponent(FieldSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PanelEmpresarialesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelHoras)
                    .addComponent(FieldHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(216, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Empresariales", PanelEmpresariales);

        ButtonRegistro.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        ButtonRegistro.setText("Nuevo Registro");
        ButtonRegistro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonRegistroMouseClicked(evt);
            }
        });
        ButtonRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonRegistroActionPerformed(evt);
            }
        });

        ButtonEnviar.setFont(new java.awt.Font("Avenir", 0, 14)); // NOI18N
        ButtonEnviar.setText("Enviar");
        ButtonEnviar.setEnabled(false);
        ButtonEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonEnviarMouseClicked(evt);
            }
        });
        ButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnviarActionPerformed(evt);
            }
        });

        ButtonIzq.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        ButtonIzq.setText("<<");

        ButtonDer.setFont(new java.awt.Font("Avenir Next", 1, 14)); // NOI18N
        ButtonDer.setText(">>");

        ButtonCargar.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        ButtonCargar.setText("Cargar");

        ButtonGuardar.setFont(new java.awt.Font("Avenir Next", 0, 14)); // NOI18N
        ButtonGuardar.setText("Guardar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(ButtonRegistro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonEnviar)
                .addGap(67, 67, 67)
                .addComponent(ButtonIzq)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonDer)
                .addGap(117, 117, 117)
                .addComponent(ButtonCargar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonGuardar)
                .addGap(18, 18, 18))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 804, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 481, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonRegistro)
                    .addComponent(ButtonEnviar)
                    .addComponent(ButtonIzq)
                    .addComponent(ButtonDer)
                    .addComponent(ButtonCargar)
                    .addComponent(ButtonGuardar))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void FieldNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldNombreActionPerformed

    private void ButtonRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonRegistroActionPerformed
        // TODO add your handling code here:
    
    }//GEN-LAST:event_ButtonRegistroActionPerformed

    private void FieldSueldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FieldSueldoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FieldSueldoActionPerformed

    private void ButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEnviarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEnviarActionPerformed

    private void ButtonRegistroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonRegistroMouseClicked
        System.out.println("Probando los eventos del ratón");
        //Quitar este sout
        ButtonEnviar.setEnabled(true);
        this.limpiarForm();
        
    }//GEN-LAST:event_ButtonRegistroMouseClicked

    private void ButtonEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEnviarMouseClicked
        Empleado tmp = new Empleado ();
        
        tmp.setNombre(this.FieldNombre.getText());
        tmp.setApPaterno(this.FieldApellidoPat.getText());
        tmp.setApMaterno(this.FieldApellidoMat.getText());
        tmp.setEdad(Integer.parseInt(this.FieldEdad.getText()));
        tmp.setCurp(this.FieldCurp.getText());
        
        tmp.getDomicilio().setCalle(this.FieldCalle.getText());
        tmp.getDomicilio().setColonia(this.FieldColonia.getText());
        tmp.getDomicilio().setNumero(this.FieldNumero.getText());
        tmp.getDomicilio().setDelegacion(this.FieldDelegacion.getText());
        tmp.getDomicilio().setEstado(this.FieldEstado.getText());
        tmp.getDomicilio().setCp(this.FieldCp.getText());
        
        tmp.setNumeroEmpleado(Integer.parseInt(this.FieldEmpleado.getText()));
        tmp.setDepartamento(this.FieldDepartamento.getText());
        tmp.setSueldo(Float.parseFloat(this.FieldSueldo.getText()));
        tmp.setHorasExtra(Integer.parseInt(this.FieldHoras.getText()));
        
        lista.add(tmp);
                this.limpiarForm();
                this.ButtonEnviar.setEnabled(false);
        System.out.println("Elementos guardados en mamoria: " + lista.size());
    }//GEN-LAST:event_ButtonEnviarMouseClicked

    private void limpiarForm(){
        this.FieldNombre.setText("");
        this.FieldApellidoPat.setText("");
        this.FieldApellidoMat.setText("");
        this.FieldEdad.setText("");
        this.FieldCurp.setText("");
        this.FieldCalle.setText("");
        this.FieldNumero.setText("");
        this.FieldColonia.setText("");
        this.FieldDelegacion.setText("");
        this.FieldEstado.setText("");
        this.FieldCp.setText("");
        this.FieldEmpleado.setText("");
        this.FieldDepartamento.setText("");
        this.FieldSueldo.setText("");
        this.FieldHoras.setText(""); 
        
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCargar;
    private javax.swing.JButton ButtonDer;
    private javax.swing.JButton ButtonEnviar;
    private javax.swing.JButton ButtonGuardar;
    private javax.swing.JButton ButtonIzq;
    private javax.swing.JButton ButtonRegistro;
    private javax.swing.JTextField FieldApellidoMat;
    private javax.swing.JTextField FieldApellidoPat;
    private javax.swing.JTextField FieldCalle;
    private javax.swing.JTextField FieldColonia;
    private javax.swing.JTextField FieldCp;
    private javax.swing.JTextField FieldCurp;
    private javax.swing.JTextField FieldDelegacion;
    private javax.swing.JTextField FieldDepartamento;
    private javax.swing.JTextField FieldEdad;
    private javax.swing.JTextField FieldEmpleado;
    private javax.swing.JTextField FieldEstado;
    private javax.swing.JTextField FieldHoras;
    private javax.swing.JTextField FieldNombre;
    private javax.swing.JTextField FieldNumero;
    private javax.swing.JTextField FieldSueldo;
    private javax.swing.JLabel LabelCalle;
    private javax.swing.JLabel LabelColonia;
    private javax.swing.JLabel LabelCp;
    private javax.swing.JLabel LabelCurp;
    private javax.swing.JLabel LabelDelegacion;
    private javax.swing.JLabel LabelDepartamento;
    private javax.swing.JLabel LabelEdad;
    private javax.swing.JLabel LabelEmpleado;
    private javax.swing.JLabel LabelEstado;
    private javax.swing.JLabel LabelHoras;
    private javax.swing.JLabel LabelNombre;
    private javax.swing.JLabel LabelNumero;
    private javax.swing.JLabel LabelSueldo;
    private javax.swing.JPanel PanelDatos;
    private javax.swing.JPanel PanelDireccion;
    private javax.swing.JPanel PanelEmpresariales;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
